CREATE TABLE players (
    user_id BIGINT PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    wins INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rooms (
    id VARCHAR(6) PRIMARY KEY,
    owner_id BIGINT REFERENCES players(userId),
    initial_chips INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
